version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
      # hide node_modules from host
      - front_node_modules:/src/node_modules
    ports:
      - '3000:3000'

volumes:
  front_node_modules:
